---
language: python
services: docker

env:
  - php_version: '7.3'

install:
  # Install Ansible.
  - pip install ansible docker
  - export ANSIBLE_FORCE_COLOR=true

  # Install role dependencies.
  # - ansible-galaxy install -r requirements.yml

script:
  # Build the container.
  # - ansible-playbook --extra-vars="@vars/7.3.yml" main.yml

  # Verify the container runs and has the correct PHP version.
  - docker run -d --name=drupal -p 8080:80 drupal:latest /usr/sbin/apache2ctl -D FOREGROUND
  - docker exec drupal php -v
  - curl http://localhost:8080/

deploy:
  provider: script
  script: bash docker-push
  on:
    branch: dev
