---
version: "3"

services:
  apache-php:
    image: heremias/apache-php:latest
    container_name: apache-php
    ports:
      - "80:80"
    restart: always
    # See 'Custom PHP codebase' for instructions for volumes.
    volumes:
      - ./web:/var/www/html:rw,delegated
    command: ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]
